version: '3.8'

services:
  # Single fluxdl node for simple deployment
  fluxdl:
    image: shohag2100/fluxdl:latest
    container_name: fluxdl
    ports:
      - "9000:9000"  # gRPC API port
      - "7000:7000"  # Raft port (for future clustering)
    environment:
      - fluxdl_NODE_ID=fluxdl-single
      - fluxdl_BIND_ADDR=0.0.0.0:9000
      - fluxdl_DATA_DIR=/data
      - fluxdl_BOOTSTRAP=true
      - fluxdl_PARTITIONS=16
      - fluxdl_REPLICATION_FACTOR=1
    volumes:
      - fluxdl-data:/data
    networks:
      - fluxdl-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: fluxdl CLI for administration
  fluxdl-cli:
    image: shohag2100/fluxdl:latest
    container_name: fluxdl-cli
    entrypoint: ["./fluxdl-cli"]
    command: ["--help"]
    networks:
      - fluxdl-network
    profiles:
      - cli
    depends_on:
      - fluxdl

volumes:
  fluxdl-data:
    driver: local

networks:
  fluxdl-network:
    driver: bridge
